import { useEffect, useRef, useState } from "react";
import type { Chart, Nullable } from "klinecharts";
import { Pencil, Plus, Trash2 } from "lucide-react";
import { cn } from "@/lib/utils";
import { detectDialect } from "@/lib/indicatorLang";
import { compilePine, type PineInput } from "@/lib/pineScript";
import { FORMULA_TEMPLATES } from "@/lib/indicatorTemplates";
import type { UserIndicator } from "@/lib/indicatorStore";
import { alignParams, parseParams, withParam, type Draft } from "./types";

/**
 * The editor tab of the script workbench (local custom ⑪).
 *
 * Beyond ⑩'s plain-text editing it does one new thing: a Pine script declares
 * its own inputs through `input.*`, so the panel is generated by actually
 * compiling the source against the chart's bars. Parsing is cheap enough to run
 * on a debounce; running is what buys us a live error message and a real form.
 */

interface EditorTabProps {
  draft: Draft;
  onDraft: (next: Draft) => void;
  items: UserIndicator[];
  error: string | null;
  getChart: () => Nullable<Chart>;
  onSave: () => void;
  onToggle: (item: UserIndicator) => void;
  onRemove: (item: UserIndicator) => void;
  onEdit: (item: UserIndicator) => void;
}

interface Probe {
  title: string;
  inputs: PineInput[];
  warnings: string[];
  lines: number;
  markers: number;
  isStrategy: boolean;
}

/** Source options are stored as an index; -1 means "whatever the script wrote". */
const SOURCE_LABELS: Record<string, string> = {
  close: "收盘价",
  open: "开盘价",
  high: "最高价",
  low: "最低价",
  volume: "成交量",
  hl2: "中间价 (H+L)/2",
  hlc3: "典型价 (H+L+C)/3",
  ohlc4: "四价均值",
};

/** Smaller than the runtime default: a preview must never stall typing. */
const PROBE_BUDGET = 6e6;

export default function EditorTab({
  draft,
  onDraft,
  items,
  error,
  getChart,
  onSave,
  onToggle,
  onRemove,
  onEdit,
}: EditorTabProps) {
  const [probe, setProbe] = useState<Probe | null>(null);
  const [probing, setProbing] = useState(false);
  const [probeError, setProbeError] = useState("");
  const getChartRef = useRef(getChart);
  getChartRef.current = getChart;
  const paramsRef = useRef(draft.paramsText);
  paramsRef.current = draft.paramsText;

  const dialect = detectDialect(draft.code);

  // Compile on a debounce whenever the source changes. Parameter edits go
  // through the ref instead, so moving a slider does not re-run the script.
  useEffect(() => {
    if (dialect !== "pine") {
      setProbe(null);
      setProbeError("");
      return;
    }
    setProbing(true);
    const timer = setTimeout(() => {
      const bars = getChartRef.current()?.getDataList() ?? [];
      if (!bars.length) {
        // No chart yet (drawer opened before data landed): stay silent rather
        // than flash "没有K线数据" at a script that is probably fine.
        setProbe(null);
        setProbeError("");
        setProbing(false);
        return;
      }
      const out = compilePine(draft.code, bars, {
        params: parseParams(paramsRef.current),
        opLimit: PROBE_BUDGET,
      });
      if ("error" in out) {
        setProbe(null);
        setProbeError(out.error ?? "编译失败");
      } else if (out.abort) {
        setProbe(null);
        setProbeError(out.abort);
      } else {
        setProbe({
          title: out.result.title,
          inputs: out.result.inputs,
          warnings: out.result.warnings,
          lines: out.result.lines.length,
          markers: out.result.markers.length,
          isStrategy: out.result.scriptKind === "strategy",
        });
        setProbeError("");
      }
      setProbing(false);
    }, 450);
    return () => clearTimeout(timer);
  }, [draft.code, dialect]);

  const inputs = probe?.inputs ?? [];

  const useTemplate = (key: string) => {
    const t = FORMULA_TEMPLATES.find((x) => x.key === key);
    if (!t) return;
    onDraft({
      id: null,
      label: t.label.replace(/（.*）$/, ""),
      kind: t.kind,
      paramsText: t.params.join(", "),
      code: t.code,
    });
  };

  return (
    <div className="space-y-4">
      {/* editor ---------------------------------------------------------- */}
      <section className="space-y-2 rounded-lg border p-2.5">
        <div className="flex items-center justify-between">
          <h3 className="text-xs font-semibold text-muted-foreground">
            {draft.id ? "编辑脚本" : "新建脚本"}
          </h3>
          <span
            className={cn(
              "rounded px-1.5 py-0.5 text-[10px]",
              dialect === "pine" ? "bg-primary/10 text-primary" : "bg-muted text-muted-foreground",
            )}
          >
            {dialect === "pine" ? "Pine Script v5" : "本地公式语言"}
          </span>
        </div>

        <div className="flex gap-2">
          <input
            value={draft.label}
            onChange={(e) => onDraft({ ...draft, label: e.target.value })}
            placeholder="脚本名称"
            className="h-7 min-w-0 flex-1 rounded border bg-background px-2 text-xs outline-none focus:border-primary"
          />
          <div className="flex items-center gap-2 text-xs">
            {(["overlay", "pane"] as const).map((k) => (
              <label key={k} className="flex cursor-pointer items-center gap-1">
                <input
                  type="radio"
                  name="ind-kind"
                  checked={draft.kind === k}
                  onChange={() => onDraft({ ...draft, kind: k })}
                />
                {k === "overlay" ? "主图" : "副图"}
              </label>
            ))}
          </div>
        </div>

        <textarea
          value={draft.code}
          onChange={(e) => onDraft({ ...draft, code: e.target.value })}
          spellCheck={false}
          rows={12}
          placeholder={"// 本地公式：return { 线名: ma(close, P[0]) };\n// 或 TradingView Pine：//@version=5 + indicator(...)"}
          className="w-full resize-y rounded border bg-background p-2 font-mono text-[11px] leading-4 outline-none focus:border-primary"
        />

        {/* live check */}
        {dialect === "pine" && (
          <p className="text-[11px] leading-4 text-muted-foreground">
            {probing ? "正在编译…" : probeError ? (
              <span className="text-red-500">{probeError}</span>
            ) : probe ? (
              <>
                编译通过：{probe.title} · {probe.lines} 条线
                {probe.markers > 0 && ` · ${probe.markers} 组标记`}
                {probe.isStrategy && " · 含策略回测"}
              </>
            ) : (
              "把光标停一会儿即可看到编译结果"
            )}
          </p>
        )}

        {/* generated parameter form */}
        {inputs.length > 0 && (
          <div className="space-y-1 rounded border bg-muted/30 p-2">
            <p className="text-[10px] font-semibold text-muted-foreground">参数（脚本内 input.* 自动生成）</p>
            <div className="grid grid-cols-2 gap-x-2 gap-y-1.5">
              {inputs.map((inp, i) => (
                <InputField
                  key={`${inp.varName}-${i}`}
                  inp={inp}
                  value={alignParams(inputs, draft.paramsText)[i]}
                  onChange={(v) => onDraft({ ...draft, paramsText: withParam(inputs, draft.paramsText, i, v) })}
                />
              ))}
            </div>
          </div>
        )}

        <details className="text-[11px]">
          <summary className="cursor-pointer text-muted-foreground">参数数组（原始值，本地语言按 P[0]… 取用）</summary>
          <input
            value={draft.paramsText}
            onChange={(e) => onDraft({ ...draft, paramsText: e.target.value })}
            placeholder="如 14, 2"
            className="mt-1 h-7 w-full rounded border bg-background px-2 font-mono text-xs outline-none focus:border-primary"
          />
        </details>

        {probe && probe.warnings.length > 0 && (
          <ul className="space-y-0.5 rounded border border-amber-500/40 bg-amber-500/5 px-2 py-1.5 text-[11px] leading-4 text-amber-600">
            {probe.warnings.map((w) => (
              <li key={w}>{w}</li>
            ))}
          </ul>
        )}

        {error && <p className="whitespace-pre-wrap text-xs text-red-500">{error}</p>}

        <div className="flex gap-2">
          <button
            type="button"
            onClick={onSave}
            className="flex items-center gap-1 rounded bg-primary px-2.5 py-1 text-xs font-medium text-primary-foreground hover:opacity-90"
          >
            <Plus size={12} /> {draft.id ? "保存并更新" : "保存并应用"}
          </button>
          {draft.id && (
            <button
              type="button"
              onClick={() => onDraft({ ...draft, id: null, label: `${draft.label} 副本` })}
              className="rounded border px-2.5 py-1 text-xs hover:bg-muted"
            >
              另存为
            </button>
          )}
        </div>
      </section>

      {/* installed list --------------------------------------------------- */}
      <section>
        <h3 className="mb-1.5 text-xs font-semibold text-muted-foreground">我的指标（勾选 = 显示在图上）</h3>
        {items.length === 0 && (
          <p className="text-xs text-muted-foreground">还没有已保存的脚本 — 写一个保存，或到「脚本库」「导入」拿现成的。</p>
        )}
        <div className="space-y-1">
          {items.map((it) => (
            <div key={it.id} className="flex items-center gap-2 rounded border px-2 py-1.5 text-xs">
              <input
                type="checkbox"
                checked={it.enabled}
                onChange={() => onToggle(it)}
                title="显示/隐藏"
                className="accent-[var(--primary)]"
              />
              <span className={cn("min-w-0 flex-1 truncate", !it.enabled && "text-muted-foreground")}>
                {it.label}
              </span>
              <span className="shrink-0 rounded bg-muted px-1 py-0.5 text-[10px] text-muted-foreground">
                {detectDialect(it.code) === "pine" ? "Pine" : "公式"}
              </span>
              <span className="shrink-0 rounded bg-muted px-1 py-0.5 text-[10px] text-muted-foreground">
                {it.kind === "overlay" ? "主图" : "副图"}
              </span>
              <button
                type="button"
                onClick={() => onEdit(it)}
                title="编辑公式"
                className="rounded p-1 text-muted-foreground hover:bg-muted hover:text-foreground"
              >
                <Pencil size={12} />
              </button>
              <button
                type="button"
                onClick={() => onRemove(it)}
                title="删除"
                className="rounded p-1 text-muted-foreground hover:bg-muted hover:text-red-500"
              >
                <Trash2 size={12} />
              </button>
            </div>
          ))}
        </div>
      </section>

      {/* local-language templates ---------------------------------------- */}
      <section>
        <h3 className="mb-1.5 text-xs font-semibold text-muted-foreground">内置公式（本地语言，一行 return 即可）</h3>
        <div className="grid grid-cols-2 gap-1.5">
          {FORMULA_TEMPLATES.map((t) => (
            <button
              key={t.key}
              type="button"
              onClick={() => useTemplate(t.key)}
              className="rounded border px-2 py-1 text-left text-xs hover:bg-muted"
            >
              {t.label}
            </button>
          ))}
        </div>
      </section>

      <CheatSheet />
    </div>
  );
}

/* -------------------------------------------------------------- input field */

function InputField({
  inp,
  value,
  onChange,
}: {
  inp: PineInput;
  value: number;
  onChange: (v: number) => void;
}) {
  const label = inp.group ? `${inp.group} · ${inp.label}` : inp.label;

  if (inp.kind === "bool") {
    return (
      <label className="col-span-2 flex cursor-pointer items-center gap-1.5 text-[11px]" title={label}>
        <input
          type="checkbox"
          checked={value !== 0}
          onChange={(e) => onChange(e.target.checked ? 1 : 0)}
          className="accent-[var(--primary)]"
        />
        <span className="truncate">{inp.label}</span>
      </label>
    );
  }

  if (inp.kind === "source" || inp.options?.length) {
    const options = inp.options ?? [];
    return (
      <label className="min-w-0 text-[11px]" title={label}>
        <span className="mb-0.5 block truncate text-muted-foreground">{inp.label}</span>
        <select
          value={String(Math.trunc(value))}
          onChange={(e) => onChange(Number(e.target.value))}
          className="h-6 w-full rounded border bg-background px-1 text-[11px] outline-none focus:border-primary"
        >
          {inp.kind === "source" && <option value="-1">脚本默认</option>}
          {options.map((opt, idx) => (
            <option key={opt} value={idx}>
              {SOURCE_LABELS[opt] ?? opt}
            </option>
          ))}
        </select>
      </label>
    );
  }

  return (
    <label className="min-w-0 text-[11px]" title={label}>
      <span className="mb-0.5 block truncate text-muted-foreground">
        {inp.label}
        {inp.min !== undefined || inp.max !== undefined ? (
          <span className="ml-1 opacity-60">
            [{inp.min ?? "-∞"}, {inp.max ?? "∞"}]
          </span>
        ) : null}
      </span>
      <input
        type="number"
        value={Number.isFinite(value) ? value : 0}
        min={inp.min}
        max={inp.max}
        step={inp.step ?? (inp.kind === "int" ? 1 : "any")}
        onChange={(e) => {
          const next = Number(e.target.value);
          if (Number.isFinite(next)) onChange(next);
        }}
        className="h-6 w-full rounded border bg-background px-1 font-mono text-[11px] outline-none focus:border-primary"
      />
    </label>
  );
}

/* --------------------------------------------------------------- cheat sheet */

function CheatSheet() {
  return (
    <details className="rounded-lg border p-2.5 text-xs">
      <summary className="cursor-pointer font-semibold text-muted-foreground">语法速查</summary>
      <div className="mt-2 space-y-1.5 leading-5 text-muted-foreground">
        <p className="font-semibold text-foreground">Pine Script v5（与 TradingView 通用）</p>
        <p>
          声明：<code className="font-mono text-foreground">indicator("名称", overlay=false)</code> /{" "}
          <code className="font-mono text-foreground">strategy("名称", initial_capital=100000)</code>
        </p>
        <p>
          参数：<code className="font-mono text-foreground">input.int(14, "周期", minval=1, maxval=200)</code>
          ，会自动生成上方表单
        </p>
        <p>
          函数：<code className="font-mono text-foreground">ta.sma ema rma atr rsi macd bb stoch supertrend crossover crossunder</code>
          、<code className="font-mono text-foreground">math.abs max min log pow</code>、历史引用{" "}
          <code className="font-mono text-foreground">close[1]</code>
        </p>
        <p>
          绘图：<code className="font-mono text-foreground">plot(序列, "名称", #2962ff, 2)</code>、
          <code className="font-mono text-foreground">plotshape(条件, "上穿", shape.triangleup, location.belowbar, #26a69a)</code>、
          <code className="font-mono text-foreground">hline(50, "中轴", color.gray)</code>
        </p>
        <p>
          下单：<code className="font-mono text-foreground">strategy.entry("L", strategy.long)</code> /{" "}
          <code className="font-mono text-foreground">strategy.close("L")</code>，回测结果看「策略报告」
        </p>
        <p>
          未支持的装饰类（label/table/bgcolor）会降级为提示，不影响主线；不支持 while / def / +=
        </p>
        <p className="pt-1 font-semibold text-foreground">本地公式语言</p>
        <p>
          变量 <code className="font-mono text-foreground">open high low close volume hl2 hlc3</code> 与参数{" "}
          <code className="font-mono text-foreground">P[0]</code>，逐行{" "}
          <code className="font-mono text-foreground">名字 = 表达式;</code>，最后一行{" "}
          <code className="font-mono text-foreground">{" return { 线名: 序列 };"}</code>；滚动函数{" "}
          <code className="font-mono text-foreground">ma ema rma stdev hh ll ref cross where</code>
        </p>
        <p>两种语言都由页面内置解释器执行，不走 eval，生产环境 CSP 下同样可跑。</p>
      </div>
    </details>
  );
}
