"""Cross-implementation reconciliation for the Pine alert bridge.

The Pine interpreter and the backend alert kernel are two independent
implementations of "does this condition hold on this bar". This test makes them
answer that question on the same literal bars, prefix by prefix, so a translated
rule that means something different on the server cannot survive CI.

The bars come from the committed fixture (generated by
``frontend/src/lib/__tests__/pineAlertBridge.test.ts``), so both sides read
identical numbers — no regeneration, no tolerance. ``minPrefix`` marks the
warm-up/seed transient (``_compute_rsi`` omits ``adjust=False`` while the
frontend ``rmaStep`` SMA-seeds) and where a shipping rule sits: a rule polls a
``count``-bar window, minimum 320. Whether the transient actually flips a
verdict is itself asserted below rather than assumed away.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, Iterator, List, Tuple

from src.alerts.conditions import EvalContext, evaluate_condition

FIXTURE_DIR = (
    Path(__file__).resolve().parents[2]
    / "frontend"
    / "src"
    / "lib"
    / "__tests__"
    / "__fixtures__"
    / "pineAlertBridge"
)


def _fixtures() -> List[Dict[str, Any]]:
    """Load every bridge fixture, refusing to treat an absent directory as empty."""
    if not FIXTURE_DIR.is_dir():
        raise AssertionError(f"fixture dir missing: {FIXTURE_DIR}")
    files = sorted(FIXTURE_DIR.glob("*.json"))
    if not files:
        raise AssertionError(f"no bridge fixtures under {FIXTURE_DIR}")
    return [json.loads(p.read_text(encoding="utf-8")) for p in files]


def _cases() -> Iterator[Tuple[Dict[str, Any], Dict[str, Any]]]:
    for fx in _fixtures():
        for case in fx["cases"]:
            yield fx, case


def test_every_case_matches_bar_by_bar() -> None:
    """One test body so a divergence names its own bar instead of vanishing.

    Compared from the second bar up, everywhere the backend has an answer. The
    measured pre-gate region is agree-or-unmeasurable (0 divergences, 13-20
    prefixes per case reporting `error`), so stopping the loop at `minPrefix`
    would have left ~590 prefixes unchecked while the name implied full parity.
    `minPrefix` still marks where a shipping rule sits (a rule polls a `count`-bar
    window, minimum 320) and the tail-signal gate below uses it.
    """
    checked_cases = 0
    for fx, case in _cases():
        checked_cases += 1
        bars = fx["bars"]
        hits = case["pineHits"]
        min_prefix = int(case["minPrefix"])
        name = fx["name"]
        assert len(hits) == len(bars), f"{name}: pineHits/bars length mismatch"
        assert min_prefix >= 100, f"{name}: minPrefix must clear the seed transient"

        compared = 0
        unmeasurable = 0
        in_shipping_region = 0
        for prefix in range(2, len(bars) + 1):
            ctx = EvalContext(symbol="BRIDGE.TEST", bars=bars[:prefix])
            res = evaluate_condition(case["condition"], ctx)
            bar = prefix - 1
            if res.error is not None:
                # Missing data is not a verdict; it is an unchecked bar.
                assert res.hit is False, f"{name}: bar {bar} claimed a hit while unmeasurable"
                unmeasurable += 1
                continue
            assert res.hit == hits[bar], (
                f"{name}: bar {bar} diverges (backend={res.hit} pine={hits[bar]}, "
                f"value={res.value}, condition={case['condition']})"
            )
            compared += 1
            if prefix >= min_prefix:
                in_shipping_region += 1
        assert in_shipping_region >= 100, (
            f"{name}: only {in_shipping_region} prefixes compared inside the shipping region"
        )
        assert compared >= 200, f"{name}: only {compared} prefixes compared at all"
        assert compared + unmeasurable == len(bars) - 1, (
            f"{name}: {len(bars) - 1 - compared - unmeasurable} bars were never probed"
        )
    assert checked_cases >= 4, (
        f"only {checked_cases} bridge cases; the roster needs at least 4"
    )


def test_short_window_reports_error_not_a_verdict() -> None:
    """Too little data must come back as `error`, never as a cleared `hit=False`.

    The bridge's whole safety argument is that the backend recomputes the same
    predicate; if a warm-up gap were silently judged False, a rule would look
    healthy while measuring nothing.
    """
    probed = 0
    for fx, case in _cases():
        period = _case_period(case)
        if period < 3:
            continue
        for prefix in (1, 2):
            if prefix > period:
                continue
            ctx = EvalContext(symbol="BRIDGE.TEST", bars=fx["bars"][:prefix])
            res = evaluate_condition(case["condition"], ctx)
            assert res.error is not None, (
                f"{fx['name']}: prefix {prefix} returned a verdict ({res.hit}) for a "
                f"{period}-bar series instead of reporting missing data"
            )
            assert res.hit is False, f"{fx['name']}: an unmeasurable read claimed a hit"
            probed += 1
    assert probed > 0, "no short-window probe ran; the roster has no period >= 3 case"


def test_each_series_carries_information() -> None:
    """Anti-false-green: an all-False series would satisfy the equality trivially."""
    seen = 0
    for fx, case in _cases():
        seen += 1
        hits = case["pineHits"]
        assert any(hits) and not all(hits), f"{fx['name']}: series carries no information"
        tail = hits[int(case["minPrefix"]):]
        assert any(tail), f"{fx['name']}: no hit inside the compared region"
        assert not all(tail), f"{fx['name']}: every compared bar hit, so False is untested"
    # The loop above is the guard against a trivial series and is itself trivial
    # on an empty roster, so the count has to be asserted outside it.
    assert seen >= 4, f"only {seen} cases inspected; a vacuous pass is not a guard"


def _case_period(case: Dict[str, Any]) -> int:
    """Longest `:N` in the condition, i.e. how many bars it needs at minimum."""
    periods = []
    for key in ("lhs", "rhs"):
        name = str(case["condition"].get(key) or "")
        if ":" in name:
            try:
                periods.append(int(name.rsplit(":", 1)[1]))
            except ValueError:
                pass
    return max(periods) if periods else 0
